### ISSUE TITLE
Redirecting to auth0

### ISSUE THREAD

**Issue by mabushey** [hpennington/kanception#24]
Not sure what is going on. I'm attempting to run on my Intranet behind Traefik with a wildcard cert.
Browser URL: `https://kan-tnf.redacted.com`

It's redirecting to Auth0. I trust Auth0 about as far as I can throw my car and have no interest in using them. How do I disable this?
Auth0 error:
```
unauthorized_client: Callback URL mismatch. http://kan-tnf.redacted.com:4000 is not in the list of allowed callback URLs 
```

More like `auth0.com` is what should not be in the list of allowed URLS.

My .env file:
```
REACT_APP_API=http://kan-tnf.redacted.com:4000
```
I would much rather specify REACT_APP_API in docker-compose.yaml. Does your app support that? 

$ docker logs -f kan-tnf-api 
```
> api@1.0.0 dev /home/ubuntu/api
> nodemon ./src/index.ts

[nodemon] 2.0.22
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node ./src/index.ts`

/home/ubuntu/api/node_modules/typescript/lib/typescript.js:43500
        ts.Debug.assert(typeof typeReferenceDirectiveName === "string", "Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.");
                 ^
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:43500:18)
    at typeDirectiveNames.map.typeDirectiveName (/home/ubuntu/api/node_modules/ts-node/src/index.ts:623:55)
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/home/ubuntu/api/node_modules/ts-node/src/index.ts:622:33)
    at actualResolveTypeReferenceDirectiveNamesWorker (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:119382:163)
    at resolveTypeReferenceDirectiveNamesWorker (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:119682:26)
    at processTypeReferenceDirectives (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:121185:31)
    at findSourceFileWorker (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:121070:21)
    at findSourceFile (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:120922:26)
    at processImportedModules (/home/ubuntu/api/node_modules/typescript/lib/typescript.js:121331:25)
[nodemon] app crashed - waiting for file changes before starting...
```

I'm not sure what all the references to `/home/ubuntu/api/node_modules/` are in the docker-compose.yaml, I do not have a user named ubuntu on my server, and it appears some of these references are on the server outside of the docker container.

Thanks for releasing this as an open source app. Please let me know if I can provide any more data.

**Comment by mabushey** [comment]
I got Kanboard running, I think this is a better fit for me.
